name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform FMT
        run: terraform fmt -check -recursive
        working-directory: 'Task 1: AWS Account Configuration/terraform-solution'

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491972551:role/GithubActionsRoleOIDC-DD
          aws-region: eu-west-1
      - name: Terraform INIT
        run: terraform init
        working-directory: 'Task 1: AWS Account Configuration/terraform-solution'
      - name: Terraform PLAN
        run: terraform plan
        working-directory: 'Task 1: AWS Account Configuration/terraform-solution'

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491972551:role/GithubActionsRoleOIDC-DD
          aws-region: eu-west-1
      - name: Terraform INIT
        run: terraform init
        working-directory: 'Task 1: AWS Account Configuration/terraform-solution'
      - name: Terraform APPLY
        run: terraform apply -auto-approve
        working-directory: 'Task 1: AWS Account Configuration/terraform-solution'